Document readline dependency
GNU readline has been a dependency since d319ebd. Document this within the initial build
instructions.

Fixes the following compiler error, due to the missing dependency:

snek-main.c:17:10: fatal error: readline/readline.h: No such file or directory
   17 | #include <readline/readline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~

Fixes: d319ebd ("Track parsing status to allow separate middle-of-statement prompts")
Signed-off-by: Rhys Kidd <rhyskidd@gmail.com>
Signed-off-by: Keith Packard <keithp@keithp.com>